name: Test and Coverage

on:
  push:
    - run: yarn install
    - run: yarn test --coverage
      env:
        CI: true

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      env:
        COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
